name: Nightly Neovim check
# Checks LSP and unit tests against new Neovim nightly once a week

on:
  schedule:
    - cron: '30 21 * * 0' # 6:30 AM JST, Monday
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL "https://github.com/neovim/neovim/releases/download/v0.9.1/nvim-linux64.tar.gz" | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }

      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make test

  lua-language-server:
    name: lua language server
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Restore cache for lua LS
        uses: actions/cache@v3
        with:
          path: _lua-ls
          key: 3.7.0
      - name: Prepare
        run: |
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL "https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz" | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }
          test -d _lua-ls || {
            mkdir -p _lua-ls
            curl -sL "https://github.com/LuaLS/lua-language-server/releases/download/3.7.0/lua-language-server-3.7.0-linux-x64.tar.gz" | tar xzf - -C "${PWD}/_lua-ls"
          }

      - name: Run check
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export PATH="${PWD}/_lua-ls/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make lua-language-server version=nightly
