name: Run tests

on:
  workflow_call:
    inputs:
      neovim_versions:
        required: true
        type: string

jobs:
  tests:
    name: unit tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        rev: ${{ fromJson(inputs.neovim_versions) }}
    steps:
      - uses: actions/checkout@v3
      - run: date +%F > todays-date
      - name: Restore cache for Neovim
        uses: actions/cache@v3
        with:
          path: _neovim
          key: ${{ matrix.rev }}-${{ hashFiles('todays-date') }}
      - name: Prepare
        run: |
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL "https://github.com/neovim/neovim/releases/download/${{ matrix.rev }}/nvim-linux64.tar.gz" | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }

      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make test
